### ISSUE TITLE
Add Tooltip for PoS tags in Similar words tab

### ISSUE THREAD

**Issue by fadmarina** [akutuzov/webvectors#15]
<img width="1027" alt="screen shot 2018-01-31 at 15 10 15" src="https://user-images.githubusercontent.com/4821909/35630962-9d334c1c-069a-11e8-8a99-ee06a141391a.png">

**Comment by akutuzov** [comment]
Thanks!
So, the idea is to give users the possibility to immediately see the list of possible PoS tags (may be, only the most frequent ones).
