### ISSUE TITLE
Font color for hovered menu items

### ISSUE THREAD

**Issue by leann-fraoigh** [akutuzov/webvectors#18]
Change font color for a more contrast one.
![3](https://user-images.githubusercontent.com/33612458/37854167-c9633300-2efa-11e8-84a9-48bb51a185ac.jpg)

**Comment by akutuzov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Цвет шрифта в меню при наведении](https://trello.com/c/v2bMFOs8/89-%D1%86%D0%B2%D0%B5%D1%82-%D1%88%D1%80%D0%B8%D1%84%D1%82%D0%B0-%D0%B2-%D0%BC%D0%B5%D0%BD%D1%8E-%D0%BF%D1%80%D0%B8-%D0%BD%D0%B0%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B8)
