### ISSUE TITLE
win textfile encoding

### ISSUE THREAD

**Issue by nlyf** [akutuzov/webvectors#20]
Понимаю что ерунда, но все же напишу.
Если выполнять [туториал](https://github.com/akutuzov/webvectors/blob/master/preprocessing/rusvectores_tutorial.ipynb) на windows машине(наверное. это странно, да) то в 3 ячейке
```python 
text = open(textfile).read()
```
будут проблемы с открытием файла из-за использования кодировки `cp1251` по умолчанию 

Может так будет приятнее?
```python 
text = open(textfile, encoding='utf-8').read()
```

**Comment by akutuzov** [comment]
Спасибо, поправим!

**Comment by lizaku** [comment]
Спасибо, исправлено!
