### ISSUE TITLE
модели cbow_fasttext не загружаются через указанную в туториале функцию

### ISSUE THREAD

**Issue by TatianaShavrina** [akutuzov/webvectors#23]
Загружаются только через KeyedVectors(), а через gensim.models.fasttext.FastText.load( не загружается
Это воспроизводится в версиях генсима 3.7, 3.6, 3.4

**Comment by akutuzov** [comment]
Тьюториал пока ещё не обновлен в соответствии с недавно релизнутыми моделями (RusVectores5).
Но да, все новые fastText-модели нужно грузить в Gensim функцией  `gensim.models.KeyedVectors.load('model.model')`, как указано в [анонсе](https://rusvectores.org/ru/rusvectores5/).

**Comment by lizaku** [comment]
Исправлено.
