### ISSUE TITLE
Language config does not work

### ISSUE THREAD

**Issue by akutuzov** [akutuzov/webvectors#3]
Setting interface_languages = en" doesn't have to seem any effect on the frontend, it is still ru/en
@ElizavetaKuzmenko

**Comment by akutuzov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать код на гитхабе приличным](https://trello.com/c/iS2bJOjL/26--)

**Comment by lizaku** [comment]
На данный момент я сделала все пункты в списке приличности, кроме самого language config. 
Мне непонятен баг, описанный как "same problem with a few /dsm link in the strings.csv file" -- те dsm-линки, которые там есть, относятся к новостям на главной странице а потому естественно они с dsm. Их выпилить в принципе?

**Comment by akutuzov** [comment]
Новостей в WebVectors вообще никаких быть не должно, это RusVectores-специфичные штуки.

**Comment by lizaku** [comment]
А может тогда выпилить русский вообще и оставить только английские строки? И объяснить, как можно дописывать новые языки.

**Comment by akutuzov** [comment]
Так вот объяснять это проще на примере какого-то языка :)

**Comment by lizaku** [comment]
Я сделала. Только я не знаю, как привязать к этому кнопку в меню вверху. И надо ли это коммитить в РусВекторес?

**Comment by akutuzov** [comment]
Ну видимо нужно передавать в шаблоны информацию о наборе языков тоже, чтобы кнопка генерилась соответствующим образом. Без этого проблема не решена.
 Это должно работать в том числе и для пары "en-rus". Если заработает, то надо и в РусВекторес коммитить.

**Comment by lizaku** [comment]
Кнопка вообще сделана для пары языков, а если их 1 или >2, то совсем ничего непонятно.

**Comment by akutuzov** [comment]
Можно пока ограничить двумя языками, а потом доработаем для любого количества.

**Comment by lizaku** [comment]
Я сделала кнопку, и у меня на локалхосте это работало. А когда я запушила на русвекторес, работать перестало, и я не знаю, что теперь делать.

**Comment by lizaku** [comment]
Ой нет, работает! Ложная тревога. Хотя не, не работает. Эта дурацкая кнопка там то есть, то нет

**Comment by akutuzov** [comment]
Не работает же.

**Comment by akutuzov** [comment]
Рестартовал апач, работает. Закрываю.
