### ISSUE TITLE
API for similarity queries

### ISSUE THREAD

**Issue by akutuzov** [akutuzov/webvectors#4]
Add option to get similarity results via API (tsv, json).

**Comment by akutuzov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API для similarity-запросов.](https://trello.com/c/8vw62BMI/46-api-similarity)

**Comment by akutuzov** [comment]
Queries in the format:
BASEURL/model/movie___actor/similarity/

**Comment by lizaku** [comment]
А почему 3 подчеркивания? А одно не катит?

**Comment by akutuzov** [comment]
Не катит, у нас же подчеркиваниями частеречные тэги отделяются.

**Comment by lizaku** [comment]
Ну ок, а дефис?

**Comment by akutuzov** [comment]
Есть слова с дефисами внутри.

**Comment by lizaku** [comment]
а два подчеркивания? =)

**Comment by akutuzov** [comment]
Если больше одного - то уже не сильно критично, сколько подчеркиваний.

**Comment by akutuzov** [comment]
Но я не настаиваю, можно и два.

**Comment by lizaku** [comment]
Эт конечно все ерунда, но я бы сделала 2 потому что:
1) чем меньше символов тем лучше (почему не 4 тогда, если не критично?)
2) когда их 2, то ещё визуально видно, что два (ну, субъективно), а когда три, то специально надо выделять и подсчитывать, сколько их там, или ты в руководстве большими буквами напишешь "ТАМ 3 ПОДЧЕРКИВАНИЯ"?
3) это уже не по теме, но может ссылки на все API сделать единообразными? Типа так: http://ling.go.mail.ru/dsm/news/человек__машина/api/similarity, то есть добавить api в адрес

**Comment by akutuzov** [comment]
Согласен. Исправишь? :)

**Comment by lizaku** [comment]
Сделано. А ты функции некоторые задокументировал? Круто!! Вот что пайчарм с людьми делает :)
Давайте ещё сделаем ветку devel и новые фичи будем коммитить туда, а не в master.

**Comment by akutuzov** [comment]
Отлично. Все выкатилось и работает. Сейчас новость напишу.
А что я там нового задокументировал? Вроде бы все и до этого было.
Про devel - а чем это облегчит нашу работу?
