### ISSUE TITLE
Communication between word2vec server and WebVectors serialized with JSON

### ISSUE THREAD

**Issue by akutuzov** [akutuzov/webvectors#5]
Now word2vec server and the main code communicate using a strange dialect of strings with separators. Should be brought to normal JSON serialization.

**Comment by akutuzov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Общение между word2vec-server и основным кодом должно происходить через нормальную JSON-сериализацию, а не таким извращенным способом как сейчас.](https://trello.com/c/CWNuv3nP/47-word2vec-server-json)

**Comment by lizaku** [comment]
Плюсую!!!

**Comment by akutuzov** [comment]
Сделаю :)
