### ISSUE TITLE
Неточность в комменте  файле  webvectors/preprocessing/rus_preprocessing_udpipe.py

### ISSUE THREAD

**Issue by sv-kopylov** [akutuzov/webvectors#55]
Коллеги, добрый день. Спасибо за проект. Увидел неточность, возможно стоит исправить.
В файле webvectors/preprocessing/rus_preprocessing_udpipe.py написано "зеленый_NOUN трамвай_NOUN", правильно   "зеленый_ADJ трамвай_NOUN" (ваша модель тоже так считает :) ).

**Comment by akutuzov** [comment]
Спасибо! Исправлено.
