### ISSUE TITLE
Redirection to "Similar Words" After Clicking on the Words

### ISSUE THREAD

**Issue by KarahanS** [akutuzov/webvectors#57]
Greetings,

I'm a computer engineering student from Turkey and currently working on creating a Turkish version of Webvectors. However, I encounter a problem. When I click on a word, it attempts to redirect me to a link where similar words are found for that specific word. For example, when I click on the word "adam", it attempts to open an URL like this: `http://127.0.0.1:5000/en/word2vec_skipgram_300/adam/`. The name of my model is correct. The problem is that there is no such page in the current version of the repository. So I couldn't find an easy way to redirect users to a similar words page for the word "adam". Am I missing anything here?

Let me provide screenshots as well:
1) Here I hover over the word "araba": ![image](https://github.com/akutuzov/webvectors/assets/44376034/cb823a60-3d4f-4c59-94dc-67ef8c16ab42)

2) This is the address it redirects me to upon clicking on it:
![image](https://github.com/akutuzov/webvectors/assets/44376034/cdb52153-59b1-47ec-89ac-2ded348c353a)

**Comment by akutuzov** [comment]
Hi,

You should look into what exactly is causing the error, what particular Python function in the `WebVectors` code.
Without this information, it is difficult to tell what is happening.

If the error happens at the visualization page, might it be the case that you turned on using TensorFlow Projector but forgot to set up your Github credentials?
